//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public bool IsActual { get; set; }
        public byte[] imagePreview { get; set; }
        public Nullable<int> ticketCount { get; set; }
        public string description { get; set; }
    }
}
